### ISSUE TITLE
Example: iPad (and mini) show white box, not menu in left drawer

### ISSUE THREAD

**Issue by jclish** [JVillella/JVFloatingDrawer#3]
When building the example program for any of our iPhone devices physical or simulated, the example app works as expected.  

When the example application is built in both the iPad simulator as well as on our iPad and iPad mini for iOS 8 on Xcode, if the user selects "left menu" the background of the view is Sky, but instead of the menu with the 2 icons on it there is only a blank white box.  Touches where the menu items should be on the white box take you to the expected new views.  
![ios_simulator_-_ipad_2_-_ipad_2___ios_8_1__12b411_](https://cloud.githubusercontent.com/assets/8339680/5793810/c01ea22a-9f06-11e4-89bb-5cb4fefb9cd5.png)

**Comment by JVillella** [comment]
Hi @jclish this likely has to do with `UIAppearance`'s default _opaque white colour_ for `UITableViewCell` selection background view. The issue is specific to the example and has no affect on the floating drawer library. Thanks for bringing it to my attention, I'll take a look shortly.

**Comment by jclish** [comment]
Many thanks for your rapid response!  I never would have gotten it without
your hint.  This goes away if you add: `[cell setBackgroundColor:[UIColor clearColor]];`

In the left view controller at the very beginning of `cellForRowAtIndexPath`.

Thanks again for a cool tool.
