### ISSUE TITLE
Would it be possible to have a swift example project?

### ISSUE THREAD

**Issue by gbertb** [JVillella/JVFloatingDrawer#4]
Would be great to see an example swift project.

**Comment by JVillella** [comment]
Yea I think so too, though the `README.md` example only involves a few initializations and assignments to get going!

**Comment by KyleGoddard** [comment]
@gbertb you may be interested in [KGFloatingDrawer](https://github.com/KyleGoddard/KGFloatingDrawer) which is a reimplementation of JVFloatingDrawer in Swift.

**Comment by varatep** [comment]
@KyleGoddard Swift 1.2 only, so not releasable yet.

Upvote on swift example.

**Comment by rlam3** [comment]
+1

**Comment by JVillella** [comment]
@KyleGoddard can we get an update on this. Implementation for Swift 1.3 in the horizon?

**Comment by KyleGoddard** [comment]
I haven't yet heard anything about Swift 1.3. 1.2 is production ready now though and can be released in the App Store.

**Comment by JVillella** [comment]
Great, then please use KGFloatingDrawer if you'd like a swift implementation.
